import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import "@/css/styles.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "First Next App",
  description: "Generated by create next app on 9/21/2023",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {/* <Nav /> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
